# @package _global_
defaults:
  - /model: default
  - /task: default
  - /datamodule: default

scheduler:
  name: cosine
  T_max: 100
  eta_min: 1e-20

loader:
  batch_size: 20

optimizer:
  lr: 6e-4
  weight_decay: 1e-5

trainer:
  devices: auto
  accelerator: cuda
  max_epochs: 40
  gradient_clip_val: 5.0
  log_every_n_steps: 100
  val_check_interval: 1.0 # val every n batches

callbacks:
  model_checkpoint:
    monitor: "val/mse_loss" # name of the logged metric which determines when model is improving
    mode: "min" # can be "max" or "min"
    save_top_k: 1 # save k best models (determined by above metric)
    save_last: True # additionaly always save model from last epoch
    auto_insert_metric_name: False
    verbose: True

  learning_rate_monitor:
    logging_interval: "step"
  
  early_stopping:
    monitor: "val/mse_loss"
    mode: "min"
    patience: 3
    verbose: True


train_type:
  name: "train"
  saved_model: null
